In [1]:
import numpy as np

In [22]:
x = np.array([[0,3,4],[2,6,4]])

In [10]:
x.shape

(2, 3)

In [12]:
x.reshape((3,2))

array([[0, 3],
       [4, 2],
       [6, 4]])

In [13]:
x.shape

(2, 3)

In [27]:
def normalyze(x):
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    x= x/x_norm
    
    return x
normalyze(x)

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

In [29]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp,axis=1,keepdims=True)
    s = x_exp/x_sum
    return s
softmax(x)

array([[0.01321289, 0.26538793, 0.72139918],
       [0.01587624, 0.86681333, 0.11731043]])

In [28]:
np.exp(x)

array([[  1.        ,  20.08553692,  54.59815003],
       [  7.3890561 , 403.42879349,  54.59815003]])